### ISSUE TITLE
Change types in userextend/models/roles/columns.yaml

### ISSUE THREAD

**Issue by Teranode** [ShawnClake/UserExtended#70]
change:
```
    description:
        label: Description
        type: tinytext

    sort_order:
        label: Priority
        type: integer
```
to
```
    description:
        label: Description
        type: text

    sort_order:
        label: Priority
        type: number
```
